### ISSUE TITLE
Can't Enable After Restart (Possible Conflict With Other Tab-Related Packages)

### ISSUE THREAD

**Issue by billyzduke** [tiger4th/vertical-tabs#1]
It was maintaining the vertical tab arrangement after restart originally, but then I installed a couple other tag plugins and I can't get the vertical tabs back (which I LOVE and NEED).

The other packages in question here are foldername-tabs by paulpflug and lucid-tabs by nmai.

**Comment by billyzduke** [comment]
Okay, I did manage to uninstall vertical-tabs package, but reinstall did not solve the issue.

**Comment by billyzduke** [comment]
Disabling those other two plugins doesn't bring back the vertical tabs either.

**Comment by tiger4th** [comment]
Thank you for reporting this issue.
I'm sorry, but I don't know how I can fix this issue.
I added a keyboard shortcut for now. (ctrl-alt-v)

Another way, you can use my vertical-tabs theme instead of this package.
https://atom.io/themes/one-dark-vertical-tabs-ui

**Comment by billyzduke** [comment]
It turns out that attempting to enable from the settings pane does not work, but enabling by using the top menu dropdown package listing does. Still resets to horizontal tabs every time I restart, but at least I can get them back now.

**Comment by tiger4th** [comment]
I could resolve this issue!
At version 0.4.0, when package is enabled, tabs are vertical every time.
