### ISSUE TITLE
One Dark Theme

### ISSUE THREAD

**Issue by whaaaley** [tiger4th/vertical-tabs#10]
I've managed to get some very atom-like styles working with vertical tabs. Would you be interested in a PR like this or do you think it would make it harder to theme?

![img](https://cl.ly/2W0s0W3q1O07/Image%202017-01-25%20at%2012.52.38%20PM.png)

**Comment by tiger4th** [comment]
Looks nice!
But if that is exclusive to One Dark, it may be better to send PR to here ↓
https://github.com/tiger4th/one-dark-vertical-tabs-ui
