### ISSUE TITLE
resizeable?

### ISSUE THREAD

**Issue by ha404** [tiger4th/vertical-tabs#11]
Would be nice to have an option to make this resizeable :)

**Comment by tiger4th** [comment]
Tab bar width is already resizable.
Is it another place that you want to resize?

**Comment by ha404** [comment]
Sorry, I meant resizable by dragging.

**Comment by tiger4th** [comment]
Hmm, Dragging is may be difficult to implement.
I thought there is no need to change width frequently, therefore I added it to settings.
Please use settings, for now.
