### ISSUE TITLE
Drop location indicator

### ISSUE THREAD

**Issue by jinglesthula** [tiger4th/vertical-tabs#12]
With horiz. tabs, when dragging a tab left or right with the mouse to reorder them, Atom shows a thick line with a carat indicating where the tab will end up when dropped.  Could something like this be added when reordering vertical tabs?  Perhaps a similar thick horizontal line w/ carat.

**Comment by tiger4th** [comment]
It was disappeared by the version up of the atom.
I fixed this issue at version 1.0.4.
