### ISSUE TITLE
After Atom 1.17.0, "Set To Right Side" has stopped working.

### ISSUE THREAD

**Issue by prateekkathal** [tiger4th/vertical-tabs#13]
Hi,

The option to set the tabs to the right side has stopped working after the latest atom update. Can you please look into it?

Atom Version - 1.17.0

Thanks,

**Comment by dcpesses** [comment]
Try apply #15 to your local files, it resolves the issue for me

**Comment by tiger4th** [comment]
I merged #15 and updated the package.
This issue was resolved at version 1.0.5.
Thanks @Mootly
