### ISSUE TITLE
setting "Tab Bar Width" doesn't work correctly

### ISSUE THREAD

**Issue by jangaba** [tiger4th/vertical-tabs#16]
After start of atom the width of tab bar is always set to default value 14.

**Comment by wenslayer** [comment]
In addition, with two panes (stacked horizontally), changing the value in the setting only changes it for the top pane, not both.

**Comment by tiger4th** [comment]
Sorry to make everyone wait.
I fixed "Tab Bar Width" setting at version 1.0.7.

**Comment by tiger4th** [comment]
@wenslayer
That's another problem.
Two panes were not considered.
I do not know if I can solve it, but I made an issue.
https://github.com/tiger4th/vertical-tabs/issues/24
