### ISSUE TITLE
Issue with width of the filename container in vertical tab pane

### ISSUE THREAD

**Issue by hilyin** [tiger4th/vertical-tabs#2]
![vert-tabs](https://cloud.githubusercontent.com/assets/6288867/16240704/48c3c27c-379f-11e6-80c6-18454a16956e.gif)

see gif

**Comment by taiga-kato** [comment]
What is your UI Theme?

**Comment by tiger4th** [comment]
What is your UI Theme?

**Comment by hilyin** [comment]
Sorry, its this one: https://atom.io/themes/base-16-ocean-dark-ui-theme

**Comment by tiger4th** [comment]
It's difficult to fully support all themes.
But you can edit your own styles. (~/.atom/styles.less)
In this case, please try this.
```
.tab-bar {
  .tab {
    &.active {
      width: 13em !important;

      .close-icon {
        margin-right: -0.5em !important;
      }
    }
  }
}
```

**Comment by hilyin** [comment]
Thanks @tiger4th, appreciate it.
