### ISSUE TITLE
toggle with keybinding

### ISSUE THREAD

**Issue by rattrayalex** [tiger4th/vertical-tabs#3]
Hi, 

Thanks for creating this package! 

I would love to be able to switch back and forth between vertical and horizontal tabs with a keyboard shortcut. Perhaps cmd+k,cmd+t ?

**Comment by tiger4th** [comment]
Hi, thank you for using.
Sorry, I removed the keyboard shortcut before.
If package has the activation commands,  Atom doesn't start the package automatically when restart Atom.
