### ISSUE TITLE
Move to right?

### ISSUE THREAD

**Issue by prateekkathal** [tiger4th/vertical-tabs#4]
Hello, 

Thanks for the plugin. 

Just wanted to know if there is any way to move the tab column to the right side instead of left? 

Waiting.

**Comment by tiger4th** [comment]
I tried it, but can't do it well for Atom's specification.
If you want to move tabs by any means, please edit your own styles. (~/.atom/styles.less)

Example. (Imperfect)
```
.editor {
  width: 85%; // Adjust for your environment
}

.tab-bar {
    position: absolute;
    right: 0;
    height: 100% !important;
    z-index: 1;
}
```

**Comment by prateekkathal** [comment]
Thanks, works perfectly fine 👍 

You may close this issue now 😃

**Comment by tiger4th** [comment]
That's good to hear 😃

**Comment by droullois** [comment]
I know it's closed, but I think this :
```
atom-pane-container {
  atom-pane {
    flex-direction: row-reverse !important;
  }
}
```
will do the job in a far better way.

Anyway, thanks for the small package.

**Comment by tiger4th** [comment]
I added tab position setting in version 1.0.0!
Thanks, @droullois
