### ISSUE TITLE
all tabs are hidden in atom 1.12.0 mac

### ISSUE THREAD

**Issue by a7madgamal** [tiger4th/vertical-tabs#8]
I'm at work now make a quick test and if you need more info from me let me know

**Comment by tiger4th** [comment]
When I checked in atom 1.12.2 mac, there was no problem.
Please update atom and try again.
Or it may be caused by an update of another package or theme.

**Comment by a7madgamal** [comment]
i think it was a conflict with another non default theme.
sorry for the trouble :)
