### ISSUE TITLE
Tabs pasted on top of each other with Seti-ui

### ISSUE THREAD

**Issue by lneveu** [tiger4th/vertical-tabs#9]
Hi,
I'm experiencing an issue with the new Atom release, **seti-ui** and **vertical-tabs**:

Tabs are pasted on top of each other:

![vertical-tabs1](https://cloud.githubusercontent.com/assets/10619585/20285836/46637160-aac4-11e6-8407-576daa85a5ea.png)

But overriding `display` attribute of `.tab-bar` fix it (replace `flex` by `block`): 

```
.tab-bar {
  display: block !important;
}
```
Are you aware of this?

Thanks 😄 

**Versions**
Atom: 1.12.2
Seti-ui: 1.3.2
Vertical-tabs: 1.0.0
OS: Windows 10

**Comment by tiger4th** [comment]
In version 1.0.1, I fixed as you said.
Thanks!
